"""One-click launch helpers for Harness-1 / BC+ training and eval."""

from trim.cli.launch import (
    ALLOWED_BENCHMARKS,
    ALLOWED_HARNESSES,
    ALLOWED_MODEL_NAMES,
    ALLOWED_TRAIN_METHODS,
    CANONICAL_COMPONENTS,
    DEFAULT_BASE_MODEL,
    LaunchError,
    LaunchSpec,
    add_common_args,
    add_eval_args,
    add_train_args,
    canonical_component_ids,
    coalition_slug,
    discover_adapter_map,
    parse_eval_args,
    parse_train_args,
    resolve_model_path,
    student_mask_for_ids,
    teacher_mask_for_ids,
    train_method_to_mode,
)

__all__ = [
    "ALLOWED_BENCHMARKS",
    "ALLOWED_HARNESSES",
    "ALLOWED_MODEL_NAMES",
    "ALLOWED_TRAIN_METHODS",
    "CANONICAL_COMPONENTS",
    "DEFAULT_BASE_MODEL",
    "LaunchError",
    "LaunchSpec",
    "add_common_args",
    "add_eval_args",
    "add_train_args",
    "canonical_component_ids",
    "coalition_slug",
    "discover_adapter_map",
    "parse_eval_args",
    "parse_train_args",
    "resolve_model_path",
    "student_mask_for_ids",
    "teacher_mask_for_ids",
    "train_method_to_mode",
]
